name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main
      - stage
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'stage'

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: let_me_in
          MYSQL_DATABASE: testing
          MYSQL_USER: homestead
          MYSQL_PASSWORD: secret
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
      redis:
        image: redis:6.2
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: zip, gd, pcntl, pdo_mysql, exif, bcmath
          ini-values: post_max_size=256M, upload_max_filesize=256M
          coverage: none

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip libzip-dev libpng-dev zip git mariadb-client

      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

      - name: Copy .env if not exists
        run: |
          if [ ! -f .env ]; then cp .env.example .env; fi

      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Generate app key
        run: php artisan key:generate

      - name: Cache vendor directory
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

  build-frontend:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v3

      - name: Restore vendor directory
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.17.0
          cache: 'npm'

      - name: Install frontend dependencies
        run: npm ci

      - name: Build frontend assets
        run: npm run build

      - name: Upload frontend build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: |
            public/build/assets/*
            public/build/*

  run-tests:
    runs-on: ubuntu-latest
    needs: install-dependencies
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: let_me_in
          MYSQL_DATABASE: testing
          MYSQL_USER: homestead
          MYSQL_PASSWORD: secret
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
      redis:
        image: redis:6.2
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: pdo_mysql

      - name: Install composer dependencies
        run: composer install --no-interaction

      - name: Run Pint code style check
        run: vendor/bin/pint --test

  package-application:
    runs-on: ubuntu-latest
    needs: [build-frontend, run-tests]
    steps:
      - uses: actions/checkout@v3

      - name: Create application.zip
        run: zip -r application.zip . -x "*.git*" "node_modules/*"

      - name: Upload packaged application artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-zip
          path: application.zip

  deploy:
    runs-on: ubuntu-latest
    needs: package-application
    environment:
      name: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || (github.ref == 'refs/heads/main' && 'production' || (github.ref == 'refs/heads/stage' && 'stage' || 'stage')) }}
    steps:
      - name: Download application artifact
        uses: actions/download-artifact@v4
        with:
          name: application-zip
          path: .

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add remote host to known_hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Copy application.zip to server
        run: scp application.zip ${{ secrets.EC2_USER }}@${{ secrets.HOST }}:/tmp/app.zip

      - name: Deploy on server
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.HOST }} bash -s << 'EOF'
          unzip -o /tmp/app.zip -d /var/www/laksiri-backoffice
          cd /var/www/laksiri-backoffice
          php artisan migrate --force
          php artisan db:seed --force
          php artisan config:clear
          php artisan cache:clear
          php artisan sidecar:deploy --activate
          EOF
